# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55592b8095be6b2a9253d8413a6774d076e2a7100d752bec197d5898d4f1f855cb196a71025e420672bc531435b83cdd8585315f084fb44e30c4948b50a8b14b

test:
  secret_key_base: f65ec82d8f1385b31ca94cae34b8e75f7581c619a25276e05ca29f8f0a76cf3d61aaa3698c63cd53d3030d080fe1dfa2605a527b98a7b306233d39c57774b992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
